version: '3.8'
services:
  app:
    image: auras0/barbershop-memo:latest
    ports:
      - "80:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-frizerie-memo.mysql.database.azure.com:3306/barbershop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&requireSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin@1234
      JAVA_TOOL_OPTIONS: "-Djava.security.egd=file:/dev/./urandom"