version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: barbershop-mysql
    environment:
      MYSQL_DATABASE: barbershop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - barbershop-net

  app:
    build: .
    container_name: barbershop-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/barbershop?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - barbershop-net

volumes:
  mysql_data:

networks:
  barbershop-net:
