services:
 
  - type: web
    name: barbershop-db
    env: docker
    region: frankfurt  
    plan: free
    image: mysql:8.0
    envVars:
      - key: MYSQL_DATABASE
        value: barbershop
      - key: MYSQL_ROOT_PASSWORD
        value: root


  - type: web
    name: barbershop-app
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
       
        value: jdbc:mysql://barbershop-db:3306/barbershop?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
