services:
  # Baza de date (folosim 5.7 pentru că e mai ușoară pe RAM)
  - type: web
    name: barbershop-db
    env: docker
    region: frankfurt
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile.db
    envVars:
      - key: MYSQL_DATABASE
        value: barbershop
      - key: MYSQL_ROOT_PASSWORD
        value: root

  # Aplicația Java
  - type: web
    name: barbershop-app
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://barbershop-db:3306/barbershop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: root
