spring.application.name=barbershop-backend

# MySQL Connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://db-frizerie-memo.mysql.database.azure.com:3306/barbershop?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&requireSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin@1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=TRACE
